#
# Macro file for "Activation.cc"
#
/control/verbose 2
/run/verbose 2
#
/testhadr/det/setMat G4_Co
#/testhadr/det/setThickness 1 cm
#/testhadr/det/setSizeYZ 1 cm
#
/run/initialize
#
/process/list
#
/gun/particle proton
/gun/energy 17 MeV
/testhadr/gun/beamSize 8 mm
/testhadr/gun/beamTime 30 min
#
/analysis/setFileName water
/analysis/h1/set 5  100  0  8   MeV	#neutrons
/analysis/h1/set 20 100  0 30  min
#/analysis/h1/set 24 100  0 30  min
#/analysis/h1/set 25 100  0 30  min
#/analysis/h1/set 26 100  0 30  min
#
/run/printProgress 1000
#
/run/beamOn 1000
